import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HomePage from "./_home";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Multi Stones</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HomePage/>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
